export enum PostsActionTypes {
  FETCH_POSTS = '[POSTS] Fetch Posts',
  FETCH_POSTS_SUCCESS = '[POSTS] Fetch Posts Success',
  FETCH_POSTS_ERROR = '[POSTS] Fetch Posts Error',
  UPDATE_POSTS = '[POSTS] Update Post',
  UPDATE_POSTS_SUCCESS = '[POSTS] Update Post Success',
  UPDATE_POSTS_ERROR = '[POSTS] Update Post Error',
  DELETE_POSTS = '[POSTS] Delete Post',
  DELETE_POSTS_SUCCESS = '[POSTS] Delete Post Success',
  DELETE_POSTS_ERROR = '[POSTS] Delete Post Error',
  CREATE_POSTS = '[POSTS] Create Post',
  CREATE_POSTS_SUCCESS = '[POSTS] Create Post Success',
  CREATE_POSTS_ERROR = '[POSTS] Create Post Error',
  LIKE_POSTS = '[POSTS] Like Post',
  LIKE_POSTS_SUCCESS = '[POSTS] Like Post Success',
  LIKE_POSTS_ERROR = '[POSTS] Like Post Error',
  REMOVE_LIKE_POSTS = '[POSTS] Remove like Post',
  REMOVE_LIKE_POSTS_SUCCESS = '[POSTS] Remove like Post Success',
  REMOVE_LIKE_POSTS_ERROR = '[POSTS] Remove like Post Error'
}
